language: python
python:
- '3.8'
node_js:
  - "11"
branches:
  only:
    - master
install:
- pip install -r requirements.txt
- nvm use 11.0.0
- npm install -g firebase-tools
- npm install
script:
- cd travisCI
- python3 -m travisCI
- cd ../
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
  token:
    secure: $FIREBASE_TOKEN
  project: resume-32229